# Generated by Django 4.1.6 on 2023-06-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regesterComplaintes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=1000, null=True)),
                ('wardNo', models.CharField(blank=True, max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('complaintes', models.CharField(blank=True, max_length=500, null=True)),
                ('aboutComplaintes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=1000, null=True)),
                ('wardNo', models.CharField(blank=True, max_length=10, null=True)),
                ('houseNo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='waterConection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('wardNo', models.CharField(blank=True, max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('houseNo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
