# Generated by Django 4.1.6 on 2023-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='waterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=1000, null=True)),
                ('wardNo', models.CharField(blank=True, max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('houseNo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
